### ISSUE TITLE
[BUG] Classification throws AttributeError 

### ISSUE THREAD

**Issue by wschlauch** [basf/mamba-tabular#109]
**Describe the bug**
When testing the MambularClassifier on another dataset, it failed due to an assertion error.
Thus, I decided to take you code example and received the same error.

**To Reproduce**
- attempt to run https://github.com/basf/mamba-tabular/blob/master/examples/example_classification.py
- 

**Expected behavior**
Expectation: classifier starts to fit to the dataset and returns a fit model

**Screenshots**
![Screenshot from 2024-08-13 14-33-09](https://github.com/user-attachments/assets/ae92de6d-b2eb-4d4e-b5fb-571a6c994ba9)
AttributeError: 'MambularClassifier' object has no attribute 'data_module'

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, Windows 10
 - Python version: Ubuntu - Python 3.10.2; Windows python 3.11.2
 - Mambular Version 0.2.1

**Comment by mkumar73** [comment]
Thank you @wschlauch  for raising the issue. We will fix it soon.

**Comment by AnFreTh** [comment]
Thanks for noticing @wschlauch. Updating the package should now fix the error. I will close this issue, but feel free to reopen or open another issue if you encounter any problems :)
