### ISSUE TITLE
quantile regression

### ISSUE THREAD

**Issue by GidonKR** [basf/mamba-tabular#119]
I would like to use this model to run a quantile regression i couldn't find an example,
also i see that you have a full distribution prediction, but what if i don't want to assume any distribution?

**Describe the solution you'd like**
if there is a possibility to run a quantile regression without any distribution assumptions
Thanks

**Comment by AnFreTh** [comment]
hi @GidonKR thanks for reaching out. So far, mambular does not support quantile regression, but if there is real interest, we will include it in the future. Just to clarify: You are looking for vanilla quantile regression, (e.g. minimization of the pinball loss) to get quantile predictions?

**Comment by GidonKR** [comment]
Hey, thanks for the quick reply, yes i was referring to minimization of the pinball loss
I would love to see it in order to compare it with the results i get with catboost.

**Comment by AnFreTh** [comment]
Alright. I will leave this issue open and close it, once the functionality is implemented.

**Comment by AnFreTh** [comment]
Included quantile regression with PR#126 and release v0.2.3. I will close this issue for now. Feel free to reopen it or open another issue for further enhancements, or if you have any issues with the current Quantile implementation.
