### ISSUE TITLE
[BUG]resnet mat error

### ISSUE THREAD

**Issue by weir12** [basf/mamba-tabular#150]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[23], line 1
----> 1 model.fit(
      2     X_train,
      3     y_train,
      4     X_val=X_test,
      5     y_val=y_test,
      6     max_epochs=100
      7 )

File ~/mambaforge/lib/python3.10/site-packages/mambular/models/sklearn_base_classifier.py:382, in SklearnBaseClassifier.fit(self, X, y, val_size, X_val, y_val, max_epochs, random_state, batch_size, shuffle, patience, monitor, mode, lr, lr_patience, factor, weight_decay, checkpoint_path, dataloader_kwargs, rebuild, **trainer_kwargs)
    372 # Initialize the trainer and train the model
    373 self.trainer = pl.Trainer(
    374     max_epochs=max_epochs,
    375     callbacks=[
   (...)
    380     **trainer_kwargs
    381 )
--> 382 self.trainer.fit(self.task_model, self.data_module)
    384 best_model_path = checkpoint_callback.best_model_path
    385 if best_model_path:

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:532, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    530 self.strategy._lightning_module = model
    531 _verify_strategy_supports_compile(model, self.strategy)
--> 532 call._call_and_handle_interrupt(
    533     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    534 )

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py:43, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     41     if trainer.strategy.launcher is not None:
     42         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
---> 43     return trainer_fn(*args, **kwargs)
     45 except _TunerExitException:
     46     _call_teardown_hook(trainer)

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:571, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    561 self._data_connector.attach_data(
    562     model, train_dataloaders=train_dataloaders, val_dataloaders=val_dataloaders, datamodule=datamodule
    563 )
    565 ckpt_path = self._checkpoint_connector._select_ckpt_path(
    566     self.state.fn,
    567     ckpt_path,
    568     model_provided=True,
    569     model_connected=self.lightning_module is not None,
    570 )
--> 571 self._run(model, ckpt_path=ckpt_path)
    573 assert self.state.stopped
    574 self.training = False

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:980, in Trainer._run(self, model, ckpt_path)
    975 self._signal_connector.register_signal_handlers()
    977 # ----------------------------
    978 # RUN THE TRAINER
    979 # ----------------------------
--> 980 results = self._run_stage()
    982 # ----------------------------
    983 # POST-Training CLEAN UP
    984 # ----------------------------
    985 log.debug(f"{self.__class__.__name__}: trainer tearing down")

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:1021, in Trainer._run_stage(self)
   1019 if self.training:
   1020     with isolate_rng():
-> 1021         self._run_sanity_check()
   1022     with torch.autograd.set_detect_anomaly(self._detect_anomaly):
   1023         self.fit_loop.run()

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:1050, in Trainer._run_sanity_check(self)
   1047 call._call_callback_hooks(self, "on_sanity_check_start")
   1049 # run eval step
-> 1050 val_loop.run()
   1052 call._call_callback_hooks(self, "on_sanity_check_end")
   1054 # reset logger connector

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py:181, in _no_grad_context.<locals>._decorator(self, *args, **kwargs)
    179     context_manager = torch.no_grad
    180 with context_manager():
--> 181     return loop_run(self, *args, **kwargs)

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py:115, in _EvaluationLoop.run(self)
    113     previous_dataloader_idx = dataloader_idx
    114     # run step hooks
--> 115     self._evaluation_step(batch, batch_idx, dataloader_idx)
    116 except StopIteration:
    117     # this needs to wrap the `*_step` call too (not just `next`) for `dataloader_iter` support
    118     break

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py:376, in _EvaluationLoop._evaluation_step(self, batch, batch_idx, dataloader_idx)
    373 self.batch_progress.increment_started()
    375 hook_name = "test_step" if trainer.testing else "validation_step"
--> 376 output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
    378 self.batch_progress.increment_processed()
    380 hook_name = "on_test_batch_end" if trainer.testing else "on_validation_batch_end"

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py:294, in _call_strategy_hook(trainer, hook_name, *args, **kwargs)
    291     return None
    293 with trainer.profiler.profile(f"[Strategy]{trainer.strategy.__class__.__name__}.{hook_name}"):
--> 294     output = fn(*args, **kwargs)
    296 # restore current_fx when nested context
    297 pl_module._current_fx_name = prev_fx_name

File ~/mambaforge/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py:393, in Strategy.validation_step(self, *args, **kwargs)
    391 with self.precision_plugin.val_step_context():
    392     assert isinstance(self.model, ValidationStep)
--> 393     return self.model.validation_step(*args, **kwargs)

File ~/mambaforge/lib/python3.10/site-packages/mambular/base_models/lightning_wrapper.py:192, in TaskModel.validation_step(self, batch, batch_idx)
    175 """
    176 Validation step for a single batch.
    177 
   (...)
    188     Validation loss.
    189 """
    191 cat_features, num_features, labels = batch
--> 192 preds = self(num_features=num_features, cat_features=cat_features)
    193 val_loss = self.compute_loss(preds, labels)
    195 self.log(
    196     "val_loss",
    197     val_loss,
   (...)
    201     logger=True,
    202 )

File ~/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py:1553, in Module._wrapped_call_impl(self, *args, **kwargs)
   1551     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552 else:
-> 1553     return self._call_impl(*args, **kwargs)

File ~/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py:1562, in Module._call_impl(self, *args, **kwargs)
   1557 # If we don't have any hooks, we want to skip the rest of the logic in
   1558 # this function, and just call forward.
   1559 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1560         or _global_backward_pre_hooks or _global_backward_hooks
   1561         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562     return forward_call(*args, **kwargs)
   1564 try:
   1565     result = None

File ~/mambaforge/lib/python3.10/site-packages/mambular/base_models/lightning_wrapper.py:110, in TaskModel.forward(self, num_features, cat_features)
     93 def forward(self, num_features, cat_features):
     94     """
     95     Forward pass through the model.
     96 
   (...)
    107         Model output.
    108     """
--> 110     return self.base_model.forward(num_features, cat_features)

File ~/mambaforge/lib/python3.10/site-packages/mambular/base_models/resnet.py:140, in ResNet.forward(self, num_features, cat_features)
    137     x = num_features + cat_features
    138     x = torch.cat(x, dim=1)
--> 140 x = self.initial_layer(x)
    141 for block in self.blocks:
    142     x = block(x)

File ~/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py:1553, in Module._wrapped_call_impl(self, *args, **kwargs)
   1551     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552 else:
-> 1553     return self._call_impl(*args, **kwargs)

File ~/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py:1562, in Module._call_impl(self, *args, **kwargs)
   1557 # If we don't have any hooks, we want to skip the rest of the logic in
   1558 # this function, and just call forward.
   1559 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1560         or _global_backward_pre_hooks or _global_backward_hooks
   1561         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562     return forward_call(*args, **kwargs)
   1564 try:
   1565     result = None

File ~/mambaforge/lib/python3.10/site-packages/torch/nn/modules/linear.py:117, in Linear.forward(self, input)
    116 def forward(self, input: Tensor) -> Tensor:
--> 117     return F.linear(input, self.weight, self.bias)

RuntimeError: mat1 and mat2 must have the same dtype, but got Long and Float

**Comment by AnFreTh** [comment]
Please provide a minimal code example to recreate the error as well as specify which package versions you are using.

**Comment by AnFreTh** [comment]
I can only imagine that this came from certain preprocessor settings. V1.0.0 should solve these. I will close this issue, however, feel free to reopen and provide a minimal code example, when the error persist after updating mambular.
