### ISSUE TITLE
[FAQ] How to load the fitted checkpoint and perform prediction directly? Thank you.

### ISSUE THREAD

**Issue by Zion-Go** [basf/mamba-tabular#153]
**Context**
Greetings. I'm new to your great framework. Through my exploring, i have a doubt and hope for some clues: When i fitted the model via 'model.fit()', the saved ckpt file does appear in the path, but when i want to reuse this ckpt via model.predict(), the error said 'model has been fitted'.

**Describe the task you are trying to achieve.**
May I ask that is there an api to load the ckpt and perform prediction directly? Thank you!

**Comment by AnFreTh** [comment]
Thanks for asking this. There is a rather ugly workaround at the moment where you would need to build the model first (unfortunately with the same data and hparams that you used for training) and then can load from the checkpoints. 

```python 
from mambular.models import MambularRegressor
model = MambularRegressor()
model.build_model(X_train, y_train)

checkpoint = torch.load(your_model_checpointpath)
model.task_model.load_state_dict(checkpoint["state_dict"])

```

Subsequently you should be able to use all functionalities again. 
Let me know if it doesnt work or there are further questions.

I will transfer this and leave it open, such that we will try and integrate a better checkpoint loading functionality.

**Comment by Zion-Go** [comment]
'<All keys matched successfully>'
It works! Thank you very much!
I haven't reached out the 'task_model' that should be loaded with the weights actually. I tried to load the weights onto the 'model' itself.
